package web

import (
	"context"
	"embed"
	"fmt"
	"html/template"
	"io"
	"log/slog"
	"net"
	"net/http"
	"strings"
	"time"

	"github.com/dmundt/go-cask/cas"
	"github.com/dmundt/go-cask/internal/index"
)

//go:embed templates/*.html
var templateFS embed.FS

//go:embed htmx.min.js
var htmxJS []byte

// Config selects viewer behavior. The viewer runs only when the caller
// (`cmd/cask web`) constructs it — there is no Enabled switch
// (viewer-security §3).
type Config struct {
	StartupToken string // generated at startup, printed once, admin role
	RoleTokens   map[string]string
	Secure       bool // serve Secure cookies (HTTPS)
}

// Server is the viewer: login, sessions, role authorization, CSRF, and the
// hypermedia pages/fragments.
type Server struct {
	store         *cas.FSRawStore
	cfg           Config
	sessions      *sessions
	loginThrottle *throttle
	tmpl          *template.Template
}

// New builds the viewer over the raw store. StartupToken is generated by the
// caller (cmd/cask) and printed once at startup.
func New(store *cas.FSRawStore, cfg Config) (*Server, error) {
	tmpl, err := template.New("viewer").Funcs(template.FuncMap{
		"shortHash": shortHash,
	}).ParseFS(templateFS, "templates/*.html")
	if err != nil {
		return nil, fmt.Errorf("parse templates: %w", err)
	}
	return &Server{
		store:         store,
		cfg:           cfg,
		sessions:      newSessions(),
		loginThrottle: newThrottle(5, time.Minute),
		tmpl:          tmpl,
	}, nil
}

// Handler returns the viewer routes with the fixed middleware order:
// auth (session) → role → CSRF (mutations) → handler. Login is public.
func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /viewer/login", s.loginPage)
	mux.HandleFunc("POST /viewer/login", s.loginPost)
	mux.HandleFunc("GET /viewer/static/htmx.min.js", s.htmx)
	mux.HandleFunc("GET /viewer/", s.require(RoleViewer, s.dashboard))
	mux.HandleFunc("GET /viewer/dashboard", s.require(RoleViewer, s.dashboardFragment))
	mux.HandleFunc("GET /viewer/objects", s.require(RoleViewer, s.objects))
	mux.HandleFunc("GET /viewer/objects/{hash}", s.require(RoleViewer, s.objectDetail))
	mux.HandleFunc("GET /viewer/objects/{hash}/raw", s.require(RoleViewer, s.objectRaw))
	mux.HandleFunc("POST /viewer/objects/{hash}/verify", s.require(RoleOperator, s.verifyFragment))
	mux.HandleFunc("POST /viewer/objects/{hash}/delete", s.require(RoleAdmin, s.deleteFragment))
	mux.HandleFunc("GET /viewer/stats", s.require(RoleViewer, s.statsPage))
	mux.HandleFunc("GET /viewer/gc", s.require(RoleAdmin, s.gcPage))
	mux.HandleFunc("POST /viewer/gc", s.require(RoleAdmin, s.gcFragment))
	return mux
}

// Roles (viewer-security §8).
const (
	RoleViewer   = "viewer"
	RoleOperator = "operator"
	RoleAdmin    = "admin"
)

// require enforces: valid session (401 empty), sufficient role (403 empty),
// CSRF on mutations (403 empty). Never discloses existence.
func (s *Server) require(role string, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		sess, ok := s.sessions.get(sessionID(r))
		if !ok {
			w.WriteHeader(http.StatusUnauthorized) // empty body
			return
		}
		if sess.Role != role && !roleAllows(sess.Role, role) {
			w.WriteHeader(http.StatusForbidden) // empty body
			return
		}
		if !csrfOK(r, sess) {
			slog.Warn("viewer csrf rejected", "path", r.URL.Path)
			w.WriteHeader(http.StatusForbidden) // empty body
			return
		}
		next(w, r)
	}
}

// roleAllows reports whether the session role satisfies the required role
// (admin ⊃ operator ⊃ viewer).
func roleAllows(sessionRole, required string) bool {
	rank := map[string]int{RoleViewer: 1, RoleOperator: 2, RoleAdmin: 3}
	return rank[sessionRole] >= rank[required]
}

// --- login ---

func (s *Server) loginPage(w http.ResponseWriter, r *http.Request) {
	s.render(w, "login", nil)
}

// loginPost validates the submitted token against the startup token (admin)
// or the configured per-role tokens, throttles failures per IP (5/min with
// backoff, viewer-security §5), and issues a session cookie.
func (s *Server) loginPost(w http.ResponseWriter, r *http.Request) {
	ip := callerIP(r)
	if s.loginThrottle.blocked(ip) {
		slog.Warn("viewer login throttled", "ip", ip)
		http.Error(w, "too many login attempts", http.StatusTooManyRequests)
		return
	}
	token := r.FormValue("token")
	var role string
	switch {
	case token == s.cfg.StartupToken:
		role = RoleAdmin
	default:
		for tok, want := range s.cfg.RoleTokens { // map is token → role
			if tok == token {
				role = want
				break
			}
		}
	}
	if role == "" {
		s.loginThrottle.fail(ip)
		slog.Warn("viewer login failed", "ip", ip) // token value never logged
		http.Error(w, "invalid token", http.StatusUnauthorized)
		return
	}
	s.loginThrottle.reset(ip)
	sess := s.sessions.create(role)
	setSessionCookie(w, sess, s.cfg.Secure)
	slog.Info("viewer login", "role", role, "ip", ip)
	http.Redirect(w, r, "/viewer/", http.StatusSeeOther)
}

// --- dashboard ---

func (s *Server) dashboard(w http.ResponseWriter, r *http.Request) {
	s.render(w, "dashboard", s.dashboardData(r.Context()))
}

func (s *Server) dashboardFragment(w http.ResponseWriter, r *http.Request) {
	s.render(w, "dashboard_panels", s.dashboardData(r.Context()))
}

type dashboardData struct {
	ObjectCount int64
	TotalSize   int64
	Algorithms  []algoRow
	Sample      []objectRow
	HasSample   bool
}

type algoRow struct {
	Algo  string
	Count int64
	Size  int64
}

type objectRow struct {
	Hash  string
	Short string
	Type  string
	Size  int64
}

func (s *Server) dashboardData(ctx context.Context) dashboardData {
	st, err := s.store.Stats(ctx)
	if err != nil {
		st = &cas.StoreStats{AlgorithmCounts: map[string]int{}}
	}
	d := dashboardData{ObjectCount: st.ObjectCount, TotalSize: st.TotalSize}
	for algo, n := range st.AlgorithmCounts {
		d.Algorithms = append(d.Algorithms, algoRow{algo, int64(n), st.TotalSize})
	}
	hashes, err := s.store.List(ctx, "")
	if err != nil {
		return d
	}
	for _, h := range index.Paginate(hashes, 0, 10) {
		d.Sample = append(d.Sample, objectRow{h.String(), shortHash(h), s.objectType(ctx, h), s.objectSize(h)})
	}
	d.HasSample = len(d.Sample) > 0
	return d
}

// --- objects list ---

func (s *Server) objects(w http.ResponseWriter, r *http.Request) {
	algo := r.URL.Query().Get("algo")
	q := strings.TrimSpace(r.URL.Query().Get("q"))
	hashes, err := s.store.List(r.Context(), algo)
	if err != nil {
		http.Error(w, "list failed", http.StatusInternalServerError)
		return
	}
	var rows []objectRow
	for _, h := range hashes {
		typ := ""
		if q != "" {
			typ = s.objectType(r.Context(), h)
			if !strings.Contains(h.String(), q) && !strings.Contains(typ, q) {
				continue
			}
		}
		rows = append(rows, objectRow{h.String(), shortHash(h), typ, s.objectSize(h)})
	}
	data := struct {
		Algo    string
		Query   string
		Objects []objectRow
		HasAny  bool
	}{algo, q, rows, len(rows) > 0}
	if r.Header.Get("HX-Request") == "true" {
		s.render(w, "object-table-fragment", data) // htmx search/refresh swap
		return
	}
	s.render(w, "objects", data)
}

// --- object detail ---

func (s *Server) objectDetail(w http.ResponseWriter, r *http.Request) {
	h, ok := parseHash(w, r)
	if !ok {
		return
	}
	data, err := s.readBounded(r.Context(), h)
	if err != nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	typ := index.EnvelopeType(data)
	s.render(w, "object", struct {
		Hash      string
		Algorithm string
		Type      string
		Size      int
		CSRF      string
		Role      string
	}{h.String(), h.Algorithm(), typ, len(data), s.csrfFor(r), s.roleFor(r)})
}

func (s *Server) objectRaw(w http.ResponseWriter, r *http.Request) {
	h, ok := parseHash(w, r)
	if !ok {
		return
	}
	data, err := s.readBounded(r.Context(), h)
	if err != nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	s.render(w, "hexdump", hexdump(data))
}

func (s *Server) verifyFragment(w http.ResponseWriter, r *http.Request) {
	h, ok := parseHash(w, r)
	if !ok {
		return
	}
	if err := s.store.Verify(r.Context(), h); err != nil {
		fmt.Fprintf(w, "<p class=\"result\">corrupt: %v</p>", template.HTMLEscapeString(err.Error()))
		return
	}
	fmt.Fprint(w, "<p class=\"result\">ok</p>")
}

func (s *Server) deleteFragment(w http.ResponseWriter, r *http.Request) {
	h, ok := parseHash(w, r)
	if !ok {
		return
	}
	if err := s.store.Delete(r.Context(), h); err != nil {
		fmt.Fprint(w, "<p class=\"result\">delete failed</p>")
		return
	}
	slog.Info("viewer audit", "action", "object.delete", "hash", h)
	fmt.Fprint(w, "<p class=\"result\">deleted</p>")
}

// --- stats ---

func (s *Server) statsPage(w http.ResponseWriter, r *http.Request) {
	st, err := s.store.Stats(r.Context())
	if err != nil {
		http.Error(w, "stats failed", http.StatusInternalServerError)
		return
	}
	type row struct {
		Algo  string
		Count int64
	}
	var rows []row
	for a, n := range st.AlgorithmCounts {
		rows = append(rows, row{a, int64(n)})
	}
	s.render(w, "stats", struct {
		ObjectCount int64
		TotalSize   int64
		Rows        []row
	}{st.ObjectCount, st.TotalSize, rows})
}

// --- gc ---

func (s *Server) gcPage(w http.ResponseWriter, r *http.Request) {
	s.render(w, "gc", struct{ CSRF string }{s.csrfFor(r)})
}

func (s *Server) gcFragment(w http.ResponseWriter, r *http.Request) {
	roots, err := parseHashLines(r.FormValue("roots"))
	if err != nil {
		fmt.Fprint(w, "<p class=\"result\">invalid root hash</p>")
		return
	}
	reachable := make(map[string]bool, len(roots))
	for _, h := range roots {
		reachable[h.String()] = true
	}
	deleted, err := gcCount(r.Context(), s.store, reachable)
	if err != nil {
		fmt.Fprint(w, "<p class=\"result\">gc failed</p>")
		return
	}
	slog.Info("viewer audit", "action", "gc", "deleted", deleted)
	fmt.Fprintf(w, "<p class=\"result\">gc: deleted %d objects</p>", deleted)
}

func (s *Server) htmx(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/javascript")
	w.Write(htmxJS)
}

// gcCount deletes every object not in reachable and returns how many were
// deleted (stats delta; cas GC itself returns no count).
func gcCount(ctx context.Context, store *cas.FSRawStore, reachable map[string]bool) (int64, error) {
	before, err := store.Stats(ctx)
	if err != nil {
		return 0, err
	}
	if err := store.GC(ctx, reachable); err != nil {
		return 0, err
	}
	after, err := store.Stats(ctx)
	if err != nil {
		return 0, err
	}
	return before.ObjectCount - after.ObjectCount, nil
}

// --- helpers ---

func (s *Server) render(w http.ResponseWriter, name string, data any) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := s.tmpl.ExecuteTemplate(w, name, data); err != nil {
		slog.Error("render", "template", name, "err", err)
	}
}

func (s *Server) readBounded(ctx context.Context, h cas.Hash) ([]byte, error) {
	rc, err := s.store.Get(ctx, h)
	if err != nil {
		return nil, err
	}
	defer rc.Close()
	return io.ReadAll(io.LimitReader(rc, 256<<10))
}

// objectSize returns an object's size in bytes (0 when unavailable).
func (s *Server) objectSize(h cas.Hash) int64 {
	n, err := s.store.Size(h)
	if err != nil {
		return 0
	}
	return n
}

func (s *Server) objectType(ctx context.Context, h cas.Hash) string {
	data, err := s.readBounded(ctx, h)
	if err != nil {
		return ""
	}
	return index.EnvelopeType(data)
}

func (s *Server) csrfFor(r *http.Request) string {
	if sess, ok := s.sessions.get(sessionID(r)); ok {
		return sess.CSRF
	}
	return ""
}

func (s *Server) roleFor(r *http.Request) string {
	if sess, ok := s.sessions.get(sessionID(r)); ok {
		return sess.Role
	}
	return ""
}

func parseHash(w http.ResponseWriter, r *http.Request) (cas.Hash, bool) {
	h, err := cas.ParseHash(r.PathValue("hash"))
	if err != nil {
		http.Error(w, "malformed hash", http.StatusBadRequest)
		return nil, false
	}
	return h, true
}

func parseHashLines(s string) ([]cas.Hash, error) {
	var out []cas.Hash
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		h, err := cas.ParseHash(line)
		if err != nil {
			return nil, err
		}
		out = append(out, h)
	}
	return out, nil
}

func shortHash(h cas.Hash) string {
	if h == nil {
		return ""
	}
	_, hexPart, _ := strings.Cut(h.String(), ":")
	if len(hexPart) > 8 {
		return hexPart[:8]
	}
	return hexPart
}

func hashWithType(h string, typ string) string {
	if typ == "" {
		return shortHash(parseHashOrNil(h))
	}
	return shortHash(parseHashOrNil(h)) + " (" + typ + ")"
}

func parseHashOrNil(s string) cas.Hash {
	h, err := cas.ParseHash(s)
	if err != nil {
		return nil
	}
	return h
}

// hexdump renders a classic 16-byte-row dump (offset, hex, ASCII).
func hexdump(data []byte) []dumpRow {
	var rows []dumpRow
	for off := 0; off < len(data); off += 16 {
		end := min(off+16, len(data))
		var hexParts []string
		var ascii strings.Builder
		for _, b := range data[off:end] {
			hexParts = append(hexParts, fmt.Sprintf("%02x", b))
			if b >= 32 && b < 127 {
				ascii.WriteByte(b)
			} else {
				ascii.WriteByte('.')
			}
		}
		rows = append(rows, dumpRow{fmt.Sprintf("%08x", off), strings.Join(hexParts, " "), ascii.String()})
	}
	return rows
}

type dumpRow struct {
	Offset string
	Hex    string
	ASCII  string
}

func callerIP(r *http.Request) string {
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}
